name: docker-pull
on: 
  [push,workflow-dispatch]
  # 
  # 添加input

jobs:
  pull-images:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: |
          echo "Greeting-------"
          echo ${{toJSON(github)}}
    
