
name: docker-pull
on: 
  [push,workflow_dispatch]
  # 
  # 添加input
env: 
  REPO_NAME: ${{vars.ALIYUN_REPO_NAME}}

jobs:
  pull-images:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4 
      - name: Print a greeting
        run: |
          echo ${{github.actor}}
          echo ${{toJSON(secrets)}}
          cat docker-push | xargs -I {} docker pull {}
          docker images
          cat docker-push | xargs -I {} docker save -o ./image/{}.tar {}
          echo ${{secrets.ALIYUN_PASSWORD}}|docker login --username ${{secrets.ALIYUN_USERNAME}} ${{env.REPO_NAME}} --password-stdin
      - name: get image
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: ./image
        
      
          
