
name: docker-pull
on: 
  [push,workflow_dispatch]
  # 
  # 添加input

jobs:
  pull-images:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4 
      - name: Print a greeting
        run: |
          echo "Greeting-------"
          echo ${{toJSON(runner)}}
          echo "next is checkout----------"
          ls
          cat docker-push
          echo "next is vars-------------"
          echo ${{toJSON(vars)}}
          echo "next is job----------"
          echo ${{toJSON(job)}}
