name: docker_images_push

on: push
env:
  REPO_NAME: ${{vars.ALIYUN_REPO_NAME}}

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: check out localrepo
        uses: actions/checkout@v4

      - name: porcess the filename
        run: |
          mapfile -t ARRAY_FILENAMES < <(cat docker-images | awk '$1{print}')
          json="Results=["
          first=true
          for item in "${ARRAY_FILENAMES[@]}"; do
            if [ "$first" = true ]; then
              first=false
            else
              json="$json,"
            fi
            json="$json\"$item\""
          done
          json="$json]"
          echo "$json"
          echo "$json" >> "$GITHUB_OUTPUT"

          
  get-images: 
    needs: define-matrix
    strategy:
      matrix:
        filename: ${{ fromJSON(needs.define-matrix.outputs.Results) }}      
    uses: ./.github/workflows/docker_pull_one.yaml
    with:
      filename: ${{matrix.filename}}
      repo_name: $REPO_NAME
    secrets: inherit

  test:
    needs: 
      - get-images
      - define-matrix
    if: ${{always()}}
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          
          echo ${{needs.define-matrix.outputs.Results}}
          echo ${{ needs.define-matrix.result }}
          echo ${{ toJSON(needs.define-matrix.outputs) }}
          echo ${{ fromJSON(needs.define-matrix.outputs.Results) }}  