name: docker_pull_one

on: 
  workflow_call:
    inputs:
      filename:
        description: 'docker file name'
        required: true
        type: string
      repo_name:
        description: 'repo name'
        default: 'docker.io'
        type: string 



jobs:
  pull-images:
    runs-on: ubuntu-latest
    steps:
      
      - name: docker login
        run: |
          echo ${{inputs.repo_name}}
          echo "${{secrets.ALIYUN_PASSWORD}}" | docker login ${{inputs.repo_name}} -u "${{secrets.ALIYUN_USERNAME}}" --password-stdin
      
      - name: docker pull
        id: docker_pull
        run: docker pull ${{ inputs.filename }}
  
      - name: save as a tar and push to Aliyun
        id: push_and_tar
        run: |
          IFS=':' read -r IMAGE_NAME IMAGE_TAG <<< "${{ inputs.filename }}" 
          IFS=$' \t\n'
          echo $IMAGE_NAME
          echo $IMAGE_TAG
          if [ -z $IMAGE_TAG ];then
            IMAGE_TAG="latest"
          fi
          export IMAGE_ID=$(docker images | grep $IMAGE_NAME | grep $IMAGE_TAG | awk '{if(NR==1)print $3}')
          docker save -o "$IMAGE_NAME"-"$IMAGE_TAG".tar $IMAGE_ID
          docker tag "$IMAGE_ID" ${{inputs.repo_name}}/${{github.actor}}/"$IMAGE_NAME":"$IMAGE_TAG"
          docker push ${{inputs.repo_name}}/${{github.actor}}/"$IMAGE_NAME":"$IMAGE_TAG"
          echo "tar_name=$IMAGE_NAME-$IMAGE_TAG.tar" >> $GITHUB_OUTPUT

      - name: display
        run: echo "${{toJSON(steps.push_and_tar.outputs)}}"

      - name: get image
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: ${{steps.push_and_tar.outputs.tar_name}}
        
      
          
