name: docker_images_push

on: push
env:
  REPO_NAME: ${{vars.ALIYUN_REPO_NAME}}

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: check out localrepo
        uses: actions/checkout@v4

      - name: porcess the filename
        run: |
          mapfile -t ARRAY_FILENAMES < <(cat docker-images|awk '$1{print}')
          QQQ=$(printf '%s\n' "${ARRAY_FILENAMES[@]}" | jq -R .| jq -s .| jq .)

          json_array='['
          for i in "${!QQQ[@]}"; do
            json_array+="\"${QQQ[$i]}\","
          done
          json_array="${json_array%,}]"
          echo "$json_array" | jq .
          echo "$json_array"

          # echo "filenames=$(echo $json_array)" >> "$GITHUB_OUTPUT"

          
  get-images: 
    needs: define-matrix
    strategy:
      matrix:
        filename: ${{fromJSON(needs.defin-matrix.outputs.filenames)}}      
    uses: ./.github/workflows/docker_pull_one.yaml
    with:
      filename: ${{matrix.filename}}
      repo_name: $REPO_NAME
    secrets: inherit

  test:
    needs: get-images
    if: ${{always()}}
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo ${{fromJSON(needs.defin-matrix.outputs.filenames)}}
