name: docker_images_push

on: push
env:
  REPO_NAME: ${{vars.ALIYUN_REPO_NAME}}

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      filenames: ${{ steps.filenames.outputs.filenames}}

    steps:
      - name: check out localrepo
        uses: actions/checkout@v4

      - name: porcess the filename
        id: filenames
        run: |
          mapfile -t ARRAY_FILENAMES < <(cat docker-images | awk '$1{print}')
          json="filenames=["
          first=true
          for item in "${ARRAY_FILENAMES[@]}"; do
            if [ "$first" = true ]; then
              first=false
            else
              json="$json,"
            fi
            json="$json\"$item\""
          done
          json="$json]"
          echo "$json"
          echo "$json" >> "$GITHUB_OUTPUT"

          
  get-images: 
    needs: define-matrix
    strategy:
      matrix:
        filename: ${{ fromJSON(needs.define-matrix.outputs.filenames) }}      
    uses: ./.github/workflows/docker_pull_one.yaml
    with:
      filename: ${{matrix.filename}}
      repo_name: $REPO_NAME
    secrets: inherit
