
name: docker-pull
on: 
  [push,workflow_dispatch]
  # 
  # 添加input

jobs:
  pull-images:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: |
          echo "Greeting-------"
          echo ${{toJSON(inputs)}}
          echo "next is steps----------"
          echo ${{toJSON(steps)}}
          echo "next is vars-------------"
          echo ${{toJSON(vars)}}
          echo "next is job----------"
          echo ${{toJSON(job)}}
