name: docker_images_push

on: push
env:
  REPO_NAME: ${{vars.ALIYUN_REPO_NAME}}

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: check out localrepo
        uses: actions/checkout@v4

      - name: porcess the filename
        run: |
          mapfile -t ARRAY_FILENAMES < <(cat docker-images|awk '$1{print}')
          json_array=$(printf '%s\n' "${ARRAY_FILENAMES[@]}" | jq -R .| jq -s .)
          echo "filenames=$json_array"
          echo "filenames=$json_array" >> "$GITHUB_OUTPUT"
          echo $json_array

          
  get-images: 
    needs: define-matrix
    strategy:
      matrix:
        filename: ${{fromJSON(needs.defin-matrix.outputs.filenames)}}      
    uses: ./.github/workflows/docker_pull_one.yaml
    with:
      filename: ${{matrix.filename}}
      repo_name: $REPO_NAME
    secrets: inherit
   
