
name: docker-pull
on: 
  [push,workflow_dispatch]
  # 
  # 添加input
env: 
  REPO_NAME: ${{vars.ALIYUN_REPO_NAME}}

jobs:
  pull-images:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4 
      - name: docker login
        run: echo "${{secrets.ALIYUN_PASSWORD}}" | docker login ${{env.REPO_NAME}} -u "${{secrets.ALIYUN_USERNAME}}" --password-stdin
      - name: docker pull
        run:  cat docker-push | xargs -I {} docker pull {}
      - name: Print a greeting
        run: |
          mkdir image
          echo ${{toJSON(steps)}}
          export DKNAME=$(cat docker-push)
          export DKID=$(docker images | grep $DKNAME | awk '{print $3}')
          docker save -o ./image/"$REPO_NAME-$DKNAME".tar $DKID
      - name: get image
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: ./image
        
      
          
